#!/usr/bin/env sh

cp test-input.js test-output.js

./index.js test-output.js
status=$?

diff ./test-expected-output.js ./test-output.js
status=$?

if [ $status -eq 0 ]; then
  echo "Success!"
  rm test-output.js
  exit 0
else 
  echo "Failed :("
  rm test-output.js
  exit -1
fi
